package zws.database;/*
DesignState - Design Compression Technology
@author: athakur
@version: 1.0
Created on February 22, 2004, 9:17 AM
Copywrite (c) 2003 Zero Wait-State Inc. All rights reserved */
import zws.exception.*;
import zws.util.Named;

import java.sql.*;
import java.util.Calendar;

public interface Database extends Named {

  public PreparedStatement prepareStatement(String sql) throws NameNotFound, NotConnected, DriverNotFound, SQLException;
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws NameNotFound, NotConnected, DriverNotFound, SQLException;
  public boolean execute(PreparedStatement s) throws SQLException;
  public void  executeUpdate(PreparedStatement s) throws SQLException;
  public ResultSet executeQuery(PreparedStatement s) throws SQLException;
  public ResultSet generateKeys(PreparedStatement s) throws SQLException;
  public boolean insertText(String table, String c1, String c2) throws NameNotFound, NotConnected, DriverNotFound, SQLException;
  public boolean insertText(String table, String c1, String c2, String c3) throws NameNotFound, NotConnected, DriverNotFound, SQLException;
  public boolean insertText(String table, String c1, String c2, String c3, String c4) throws NameNotFound, NotConnected, DriverNotFound, SQLException;
  public String limitResults(String sql, int rows);
  public String formatDate(Calendar c) throws InvalidSyntax;
  public Calendar parseDate(String s) throws InvalidSyntax;
  
  public String getName();
  public String getDatabaseType();
  
  public String getHost();
  public String getPort();
  public String getDatabaseName();
  public String getUsername();
  public String getPassword();
  public long getConnectionTimeout(); //seconds
  public void setConnectionTimeout(long l); //seconds

  public String getDriverFQCN();
  public String getConnectionURL() throws InvalidConfiguration;

  //public Connection connect() throws NotConnected, DriverNotFound;
  //public void release(Connection con);
  public void closeAllConnections();
}
